Lesson 1.8: Data Fetching Data Refetching Memoized Handlers
Nata-Kalina/react-todo-new pull request #8
Opened 2024-05-12 02:27 UTC by Nata-Kalina

Was not able to handle POST request.
Get 403 error.

2024-05-13 04:36 UTC, gsvidal requested changes
There's a bug when you add any todo, an empty todo title is created in the app, try to fix that.

2024-05-13 04:36 UTC, gsvidal commented on src/App.jsx
> +          comletedAt: todo.fields.completedAt,
There's a typo here

2024-05-13 04:40 UTC, gsvidal commented on src/AddTodoForm.jsx
> +    setTodoTitle('');
Good use of validation for the todo length. You could improve that using the trim method in case the user inputs a "   " string (many blank spaces)

2024-05-14 21:58 UTC, Nata-Kalina commented on src/App.jsx
> +          comletedAt: todo.fields.completedAt,
Thank you! I found the typo

2024-05-15 23:04 UTC, Nata-Kalina commented
Hi @gsvidal! I would love to get your feedback when you will have a chance to look at my PR.

2024-05-16 04:20 UTC, gsvidal approved these changes
Excelent, everything looks fine. If you have time I encourage you to make the update and delete functionalities as well.

2024-05-16 22:32 UTC, merged